#+TITLE: Data visualization by Toby Dylan Hocking, PhD
#+OPTIONS: num:nil 
#+SETUPFILE: ~/src/org-html-themes/setup/theme-readtheorg.setup

**** Email: toby.hocking@r-project.org

**** Data visualization consulting services

I am an expert in designing interactive and animated graphics that
reveal patterns in big data sets. For example, based on [[http://datacatalog.worldbank.org/][data from the
World Bank]], I designed a data visualization that shows how life
expectancy and fertility rates of countries changed between
1960-2010. Interactive features can be used to highlight and browse
different regions, countries, and years.

[[http://cbio.ensmp.fr/~thocking/WorldBank-facets/][https://raw.githubusercontent.com/tdhock/animint/master/screencast-WorldBank.gif]]

I am available for hire as a consultant for:
- Designing custom visualizations for your big data sets. Send me your
  data set and I will write custom code that produces an informative
  visualization.
- Teaching you how to use free/open-source software for data
  visualization (R+ggplot2+animint, JavaScript+D3). Explain to me what
  kinds of data visualizations you would like to make, and I will
  create a custom seminar tailored to your particular needs.  [[https://github.com/tdhock/tutorials#data-visualization][List of
  previous teaching about data visualization]].

**** Data visualization software products

I have written several free/open-source software packages for data
visualization.
- Automatic legends in modern plotting packages like ggplot2 can
  sometimes be confusing. The [[https://github.com/tdhock/directlabels][directlabels]] R package makes it easy to
  replace confusing legends with direct labels.
- [[https://github.com/tdhock/animint][animint]] makes it easy to design complex interactive data
  visualizations, by adding the clickSelects and showSelected keywords
  to the grammar of graphics (R+JavaScript code).
I am available for hire for teaching you about these software
packages.
