#+TITLE: Toby Dylan Hocking, PhD
#+OPTIONS: num:nil 
#+SETUPFILE: ~/src/org-html-themes/setup/theme-readtheorg.setup

**** Email: tdhock5@gmail.com

**** Machine learning and data visualization consulting services

I am passionate about analysis, predictive modeling, and visualization
of big data. I am available for hire as a consultant for:
- [[file:machine-learning.org][Machine learning]].
- [[file:data-visualization.org][Data visualization]].
- Programming R packages or Python modules (including C/C++ code).
- Teaching any of the above subjects. [[https://github.com/tdhock/tutorials][List of previous teaching]].

To schedule a free first meeting to estimate my fees for your project,
please contact me via email with:
- a list of times you would be available to meet (Skype, Google
  Hangout, or face-to-face in Montreal), and
- a description of your project.

Bio: born in California (1984), Bachelors at UC Berkeley (2006), PhD
in Paris (2012), currently a post-doctoral researcher at McGill in
Montreal. Author of several free/open-source
R/Python/C/C++/JavaScript packages, [[https://github.com/tdhock?tab%3Drepositories][available on GitHub]]. More complete
[[file:TDHockingResume-2015-10-06.pdf][1-page CV]].

**** Services de consultation pour l'apprentissage artificiel et la visualisation de données

Je suis passionné par l'analyse, la modélisation prédictive, et la
visualisation des grands jeux de données. Je suis disponible pour
travailler en :
- [[file:machine-learning.org][Apprentissage artificiel]]. 
- [[file:data-visualization.org][Visualisation de données]].
- Programmation des paquets R ou modules Python, y compris C/C++. 
- Enseignement dans les sujets ci-dessus. Je peux parler en français
  alors que j'écris les [[https://github.com/tdhock/tutorials][slides]] en anglais.

SVP prendre rendez-vous par courriel pour discuter mes frais de
consultation sur votre projet. N'oubliez pas de m'écrire :
- vos disponibilités (par Skype, Google Hangout, ou
  en personne à Montréal), et
- un résumé de votre projet.

Bio : né en Californie (1984), diplôme de Bachelor à UC Berkeley
(2006), doctorat à Paris (2012), actuellement chercheur post-doctoral
à McGill, Montréal. Auteur de plusieurs bibliothèques de logiciel
libre dans R/Python/C/C++/JavaScript, [[https://github.com/tdhock?tab%3Drepositories][disponible sur GitHub]]. Plus
d'infos en anglais [[file:TDHockingResume-2015-10-06.pdf][sur mon CV]].
