#+TITLE: Machine learning by Toby Dylan Hocking, PhD
#+OPTIONS: num:nil 
#+SETUPFILE: ~/src/org-html-themes/setup/theme-readtheorg.setup

**** Email: tdhock5@gmail.com

**** Machine learning consulting services

I am an expert in designing and implementing machine learning models
for recognizing and predicting patterns in big data sets. I have
published several academic papers at the major machine learning
conferences ([[file:TDHockingResume-2015-10-06.pdf][CV]]).

I am available for hire as a consultant for:
- Designing new machine learning models for your data. Send me your
  data set along with a description of what you are trying to predict,
  and I will design a model and write custom code for you.
- Teaching you how to use free/open-source software for machine
  learning (R/Python/C/C++). Explain to me what kinds of machine
  learning models and/or software tools you would like to use, and I
  will create a custom seminar for your particular needs. [[https://github.com/tdhock/tutorials#machine-learning][List of
  previous teaching about machine learning]].

**** Machine learning software products

I have written several free/open-source software packages for machine
learning.
- [[http://clusterpath.r-forge.r-project.org/][clusterpath]] implements an algorithm for unsupervised hierarchical
  clustering (R package with C++ code).
- [[https://github.com/tdhock/rankSVMcompare][rankSVMcompare]] implements a supervised learning algorithm for
  ranking and comparing objects, based on labeled preference pairs (R
  package).
- [[https://github.com/tdhock/WeightedROC][WeightedROC]] can compute a ROC curve for a weighted binary
  classification problem (R package).
- [[https://github.com/tdhock/PeakSegJoint][PeakSegJoint]] implements convex and discrete optimization algorithms
  for supervised peak detection (R package with C code).
I am available for hire for teaching you about these software
packages.
