#+TITLE: Programming by Toby Dylan Hocking, PhD
#+OPTIONS: num:nil 
#+SETUPFILE: ~/src/org-html-themes/setup/theme-readtheorg.setup

**** Email: toby.hocking@r-project.org

**** Programming consulting services

I am an expert programmer of R packages and Python modules for
analyzing big data sets.

I am available for hire as a consultant for:
- Programming new R packages or Python modules (including C/C++
  code). Send me a description of what you want the code to do, and I
  will write the program for you (along with test cases and
  documentation).
- Re-writing existing packages to minimize execution time and memory
  usage. Is your existing code too slow or too memory-intensive for
  your big data sets? Send me your code and I will use benchmarking
  tools to find the bottlenecks, then re-write the parts necessary to
  get the performance you need.
- Teaching you how to write optimized code (R, Python, C, C++, regular
  expressions). Explain to me what kinds of problems you would like
  to solve, and I will create a custom seminar for your particular
  needs. [[https://github.com/tdhock/tutorials#programming-for-data-analysis][List of previous teaching about programming for data
  analysis]].
  
**** Progamming software products

I have written several free/open-source software packages for
programming with data.
- I wrote the C code that interfaces R with the [[http://pcre.org/][Perl-Compatible
  Regular Expressions]] library, and permits named capture regular
  expressions ([[https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=14518][patch]]). My code has been distributed with every copy of
  R since version 2.14 in 2011.
- [[https://github.com/tdhock/namedCapture][namedCapture]] is an R package which provides a convenient output
  format for data extracted using a named capture regular expression.
- I designed and wrote the part of the [[https://github.com/ropensci/plotly][plotly]] package which converts a
  =ggplot= (an R object) to a JSON file for upload to the [[https://plot.ly/][plot.ly]]
  server.
- [[https://github.com/tdhock/memtime][memtime]] can be used for memory benchmarking R code.
- I wrote the =str.extractall= method for named capture regular
  expressions in [[http://pandas.pydata.org/][pandas]] ([[https://github.com/pydata/pandas/pull/11386][PR]]).
- [[https://github.com/tdhock/requireGitHub][requireGitHub]] can be used to record and install any version of any R
  package on GitHub, thus facilitating reproducible computations.
- [[https://github.com/tdhock/revector][revector]] is an R package with C code for vectors of regular
  expressions.
- [[https://github.com/tdhock/inlinedocs][inlinedocs]] makes it easy to maintain R package documentation, by
  converting comments in R code to documentation files (Rd).
I am available for hire for teaching you about these software
packages.
