---
layout: post
title: Generalization to new subsets in R
description: Coding non-standard cross-validation 
---

```{r Ropts, echo=FALSE}
repo.dir <- normalizePath("..")
post.id <- "2023-12-07-dt-particularities"
fig.path <- file.path(repo.dir, "assets", "img", post.id)
knitr::opts_chunk$set(
  dpi=100,
  fig.path=paste0(fig.path, "/"),
  fig.width=8,
  fig.process=function(path)sub(repo.dir, "", path, fixed=TRUE),
  fig.height=4)
if(FALSE){
  knitr::knit(paste0(post.id, ".Rmd"))
}
```

The goal of this blog post is to explain the similarities and
differences between base R data frames, and data tables.

## Difference in assignment

```{r}
library(data.table)
syntax <- function(type, name, cols, op, code){
  mcall <- match.call()
  dt.args <- lapply(as.list(mcall[-1]), paste)
  do.call(data.table, dt.args)
}
syntax.tab <- rbind(
  syntax(frame, literal, one, get, "DF$colA"),
  syntax(frame, literal, one, set, "DF$colA<-valA"),
  syntax(table, literal, one, get, "DT[,colA]"),
  syntax(table, literal, one, set, "DT[,colA:=valA]"),
  syntax(frame, variable, multiple, set, 'DF[col.name.vec] <- val.list'),
  syntax(table, variable, multiple, set, 'DT[, (col.name.vec) := val.list]'),
  syntax(frame, variable, one, set, 'DF[[one.col.name]] <- valA'))
options(width=100)
dcast(syntax.tab, op + name + cols ~ type, value.var="code")  
```

### Reference semantics

TODO

```{r}
dt.outside <- data.table(x=1:3)
double_square_brackets <- function(dt.inside, variable, value){
  dt.inside[[variable]] <- value #makes a copy!
}
do_set <- function(dt.inside, variable, value){
  set(dt.inside, j=variable, value=value)
}
double_square_brackets(dt.outside, "five", 5)
dt.outside
do_set(dt.outside, "five", 5)
dt.outside
```
