---
layout: post
title: Optimal partitioning in R
description: Vectorized implementations
---

```{r Ropts, echo=FALSE, results='hide'}
repo.dir <- normalizePath("..")
post.id <- "2024-11-07-OPART-data-table"
fig.path <- paste0(file.path(repo.dir, "assets", "img", post.id), "/")
dir.create(fig.path, showWarnings = FALSE, recursive = TRUE)
knitr::opts_chunk$set(
  dpi=100,
  fig.path=fig.path,
  fig.width=10, ## TODO python figures wider? look at prev issue.
  fig.process=function(path)sub(repo.dir, "", path, fixed=TRUE),
  fig.height=4)
conda.env <- "2023-08-deep-learning"
conda.env <- "torch-aum"
RETICULATE_PYTHON <- sprintf(if(.Platform$OS.type=="unix")
  ##"/home/tdhock/.local/share/r-miniconda/envs/%s/bin/python"
  "/home/tdhock/miniconda3/envs/%s/bin/python"
  else "~/AppData/Local/Miniconda3/envs/%s/python.exe", conda.env)
Sys.setenv(RETICULATE_PYTHON=RETICULATE_PYTHON)
##reticulate::use_condaenv(dirname(RETICULATE_PYTHON), required=TRUE)
in_render <- !is.null(knitr::opts_knit$get('rmarkdown.pandoc.to'))
in_knit <- isTRUE(getOption('knitr.in.progress'))
options(width=120)
if(FALSE){
  knitr::knit(paste0(post.id, ".Rmd"))
}
```

The goal of this post is to show how to implement the optimal
partitioning algorithm in R.

```{r}
library(ggplot2)
library(data.table)
N.per.seg <- 100000
set.seed(1)
N.segs <- 3
N.dim <- 2
(mean.mat <- matrix(
  runif(N.segs*N.dim, 0, 10),
  N.segs, N.dim))
sim.dt.list <- list()
true.mean.dt.list <- list()
for(seg.i in 1:N.segs){
  for(dim.i in 1:N.dim){
    mean.param <- mean.mat[seg.i, dim.i]
    num.vec <- rnorm(N.per.seg, mean.param)
    true.mean.dt.list[[paste(seg.i, dim.i)]] <- data.table(
      seg.i, dim.i, mean.param,
      first.i=(seg.i-1)*N.per.seg+1, 
      last.i=seg.i*N.per.seg, 
      parameter="true"
    )[, `:=`(
      start=first.i-0.5,
      end=last.i+0.5
    )]
    sim.dt.list[[paste(seg.i, dim.i)]] <- data.table(
      seg.i, dim.i, i.in.seg=1:N.per.seg, value=num.vec)
  }
}
true.mean.dt <- rbindlist(true.mean.dt.list)
(sim.dt <- rbindlist(
  sim.dt.list
)[
, data.i := seq_along(seg.i)
, by=dim.i][])

ggplot()+
  geom_point(aes(
    data.i, value),
    shape=1,
    data=sim.dt)+
  facet_grid(dim.i ~ ., labeller=label_both)+
  geom_segment(aes(
    first.i, mean.param,
    color=parameter,
    xend=last.i, yend=mean.param),
    size=2,
    data=true.mean.dt)

OPART_dt_update <- function(x.mat, penalty){
  n.data <- nrow(x.mat)
  best.change <- rep(NA,n.data)
  best.cost <- rep(NA,n.data)
  n.dim <- ncol(x.mat)
  best.param <- matrix(NA,n.data,n.dim)
  cum.mat <- rbind(0,apply(x.mat,2,cumsum))
  sq.mat <- rbind(0,apply(x.mat^2,2,cumsum))
  best.cost <- best.change <- best.Nsegs <- rep(NA,nrow(x.mat))
  for(last.seg.end in seq_along(best.cost)){
    last.seg.start <- seq(1, last.seg.end)
    get_sum <- function(m){
      matrix(
        m[last.seg.end+1,], last.seg.end, ncol(m), byrow=TRUE
      )-m[last.seg.start,]
    }
    N.vec <- last.seg.end-last.seg.start+1
    candidate.dt <- data.table(
      last.seg.start,
      last.seg.cost=rowSums(get_sum(sq.mat)-get_sum(cum.mat)^2/N.vec)
    )[
      last.seg.start==1, `:=`(
        prev.cost=0,
        Nsegs=1
      )
    ][
      last.seg.start>1, `:=`(
        prev.cost=best.cost[last.seg.start-1]+penalty,
        Nsegs=best.Nsegs[last.seg.start-1]+1L
      )
    ][
    , total.cost := prev.cost + last.seg.cost
    ][]
    best.row <- candidate.dt[which.min(total.cost)]
    best.cost[last.seg.end] <- best.row$total.cost
    best.Nsegs[last.seg.end] <- best.row$Nsegs
    best.change[last.seg.end] <- best.row$last.seg.start
  }
  data.table(best.change, best.cost, best.Nsegs)
}

OPART_dt <- function(x.mat, penalty){
  n.data <- nrow(x.mat)
  best.change <- rep(NA,n.data)
  best.cost <- rep(NA,n.data)
  n.dim <- ncol(x.mat)
  best.param <- matrix(NA,n.data,n.dim)
  cum.mat <- rbind(0,apply(x.mat,2,cumsum))
  sq.mat <- rbind(0,apply(x.mat^2,2,cumsum))
  best.cost <- best.change <- rep(NA,nrow(x.mat))
  for(last.seg.end in seq_along(best.cost)){
    last.seg.start <- seq(1, last.seg.end)
    get_sum <- function(m){
      matrix(
        m[last.seg.end+1,], last.seg.end, ncol(m), byrow=TRUE
      )-m[last.seg.start,]
    }
    N.vec <- last.seg.end-last.seg.start+1
    candidate.dt <- data.table(
      last.seg.start,
      last.seg.cost=rowSums(get_sum(sq.mat)-get_sum(cum.mat)^2/N.vec)
    )
    ## [
    ##   ## last.seg.start==1, `:=`(
    ##   ##   prev.cost=0
    ##   ## )
    ## ][
    ##   ## last.seg.start>1, `:=`(
    ##   ##   prev.cost=best.cost[last.seg.start-1]+penalty
    ##   ## )
    ## ][
    ## ##, total.cost := prev.cost + last.seg.cost
    ## ][]
    last.seg.cost <- rowSums(get_sum(sq.mat)-get_sum(cum.mat)^2/N.vec)
    prev.cost <- ifelse(last.seg.start==1, 0, best.cost[last.seg.start-1]+penalty)

    total.cost <- prev.cost + last.seg.cost
    best.i <- which.min(total.cost)
    best.cost[last.seg.end] <- total.cost[best.i]
    best.change[last.seg.end] <- best.i
  }
  data.table(best.change, best.cost)
}

sim.wide <- dcast(sim.dt, data.i ~ dim.i, value.var="value")
sim.mat <- as.matrix(sim.wide[,-1])
penalty <- 15
why.slow <- OPART_dt_update(sim.mat,penalty)
mod.res <- OPART_dt(sim.mat,penalty)

OPART_fast <- function(sim.mat,penalty){
  cum.data <- rbind(0,apply(sim.mat,2,cumsum))
  cum.squares <- rbind(0,apply(sim.mat^2,2,cumsum))
  best.cost <- rep(NA_real_,nrow(sim.mat))
  best.change <- rep(NA_integer_,nrow(sim.mat))
  for(last.seg.end in seq_along(best.cost)){
    last.seg.start <- seq(1, last.seg.end)
    get_sum <- function(m){
      matrix(
        m[last.seg.end+1,], last.seg.end, ncol(m), byrow=TRUE
      )-m[last.seg.start,]
    }
    N.vec <- last.seg.end-last.seg.start+1
    last.seg.cost <- rowSums(get_sum(cum.squares)-get_sum(cum.data)^2/N.vec)
    other.cost <- c(0,best.cost[last.seg.start-1]+penalty)
    total.cost <- other.cost+last.seg.cost
    best.i <- which.min(total.cost)
    best.change[last.seg.end] <- best.i
    best.cost[last.seg.end] <- total.cost[best.i]
  }
  data.table(best.change,best.cost)
}
obase <- OPART_fast(sim.mat,penalty)

suffix.vec <- c("dt","dt_update","fast")
expr.list <- atime::atime_grid(
  list(FUN=paste0("OPART_",suffix.vec)),
  OPART=FUN(x.mat,15),
  symbol.params = "FUN")
ores <- atime::atime(
  N=unique(as.integer(10^seq(1,3,by=0.25))),
  setup={
    str(N)
    x.mat <- sim.mat[1:N,]
  },
  seconds.limit=0.1,
  expr.list=expr.list)
plot(ores)
oref <- atime::references_best(ores)
plot(oref)
all.equal(why.slow$best.cost, obase$best.cost)

decode <- function(best.change){
  seg.dt.list <- list()
  last.i <- length(best.change)
  while(print(last.i)>0){
    first.i <- best.change[last.i]
    seg.dt.list[[paste(last.i)]] <- data.table(
      first.i, last.i)
    last.i <- first.i-1L
  }
  rbindlist(seg.dt.list)[seq(.N,1)]
}
decode(obase$best.change)

min.list <- list(
  base=function(x){
    i <- which.min(x)
    x[i]
  },
  dt=function(x){
    data.table(x)[which.min(x), x]
  })
expr.list <- atime::atime_grid(
  list(fun=names(min.list)),
  min=min.list[[fun]](x.vec))
ares <- atime::atime(
  setup={
    set.seed(1)
    x.vec <- rnorm(N)
  },
  expr.list=expr.list)
plot(ares)

```

## Conclusions

TODO

## Session info

```{r}
sessionInfo()
```
