---
layout: post
title: Collaborations not allowed
description: Parsing 
---

```{r Ropts, echo=FALSE}
repo.dir <- normalizePath("..")
post.id <- "2024-09-09-collaborations-not-allowed"
fig.path <- file.path(repo.dir, "assets", "img", post.id)
knitr::opts_chunk$set(
  dpi=100,
  fig.path=paste0(fig.path, "/"),
  fig.width=10,
  fig.process=function(path)sub(repo.dir, "", path, fixed=TRUE),
  fig.height=2)
options(width=120)
if(FALSE){
  knitr::knit(paste0(post.id, ".Rmd"))
}
```

The goal of this post is to explore what countries and institutions are not allowed in collaborations with researchers in Canada.

## Introduction 

```{r}
orgs.html <- "~/canada-list-of-risky-research-orgs.html"
if(!file.exists(orgs.html)){
  u <- "https://science.gc.ca/site/science/en/safeguarding-your-research/guidelines-and-tools-implement-research-security/sensitive-technology-research-and-affiliations-concern/named-research-organizations"
  download.file(u, orgs.html)
}
library(data.table)
```

```html
<li><strong>A.A. Kharkevich Institute for Information Transmission Problems, IITP, Russian Academy of Sciences</strong> (Russia)</li>
<li><strong>Academy of Military Medical Sciences</strong> (People’s Republic of China)
<p>Known alias(es): AMMS</p>
</li>
<li><strong>Academy of Military Science</strong> (People’s Republic of China)
<p>Known alias(es): AMS</p>
</li>
<li><strong>Aerospace Research Institute</strong> (Iran)
<p>Known alias(es): ARI</p>
</li>
```

## Conclusions

TODO

## Session info

```{r}
sessionInfo()
```
