---
layout: post
title: Exponential time TRE
description: A demonstration of atime
---

```{r Ropts, echo=FALSE, results='hide'}
repo.dir <- normalizePath("..")
post.id <- "2024-11-12-exp-time-TRE"
fig.path <- paste0(file.path(repo.dir, "assets", "img", post.id), "/")
dir.create(fig.path, showWarnings = FALSE, recursive = TRUE)
knitr::opts_chunk$set(
  dpi=100,
  fig.path=fig.path,
  fig.width=10, ## TODO python figures wider? look at prev issue.
  fig.process=function(path)sub(repo.dir, "", path, fixed=TRUE),
  fig.height=4)
conda.env <- "2023-08-deep-learning"
conda.env <- "torch-aum"
RETICULATE_PYTHON <- sprintf(if(.Platform$OS.type=="unix")
  ##"/home/tdhock/.local/share/r-miniconda/envs/%s/bin/python"
  "/home/tdhock/miniconda3/envs/%s/bin/python"
  else "~/AppData/Local/Miniconda3/envs/%s/python.exe", conda.env)
Sys.setenv(RETICULATE_PYTHON=RETICULATE_PYTHON)
##reticulate::use_condaenv(dirname(RETICULATE_PYTHON), required=TRUE)
in_render <- !is.null(knitr::opts_knit$get('rmarkdown.pandoc.to'))
in_knit <- isTRUE(getOption('knitr.in.progress'))
options(width=120)
if(FALSE){
  knitr::knit(paste0(post.id, ".Rmd"))
}
```

The goal of this post is to use atime to see if TRE is exponential time as was claimed in <https://github.com/laurikari/tre/issues/54>

```{r}
n2pat <- list(
  "{N}"=function(N)sprintf("{%d}",N),
  "{2}..."=function(N)paste(rep("{2}",N),collapse=""))
expr.list <- atime::atime_grid(
  list(
    GREP=c("grep","agrep"),
    PAT=names(n2pat)
    ),
  TRE=GREP(pattern.list[[PAT]], "x"),
  symbol.params = "GREP")
ares <- atime::atime(
  N=unique(as.integer(2^seq(1,5,l=20))),
  expr.list=expr.list,
  setup={
    pattern.list <- lapply(n2pat, function(f)f(N))
    str(pattern.list)
  })
plot(ares)
arefs <- atime::references_best(ares)
plot(arefs)
```

Above we only observe exponential time for `grep("{2}..{2}", "x")` and same for below (with `x?` added to pattern).

```{r}
ares.x <- atime::atime(
  N=unique(as.integer(2^seq(1,5,l=20))),
  expr.list=expr.list,
  setup={
    pattern.list <- lapply(n2pat, function(f)paste0("x?",f(N)))
    str(pattern.list)
  })
plot(ares.x)

arefs.x <- atime::references_best(ares.x)
plot(arefs.x)
```
## Conclusions

TODO

## Session info

```{r}
sessionInfo()
```
