---
layout: post
title: Parsing check logs using regular expressions
description: A demonstration of nc R package
---

```{r Ropts, echo=FALSE}
repo.dir <- normalizePath("..")
post.id <- "2024-01-19-nc-parse-check-logs"
fig.path <- file.path(repo.dir, "assets", "img", post.id)
knitr::opts_chunk$set(
  dpi=100,
  fig.path=paste0(fig.path, "/"),
  fig.width=8,
  fig.process=function(path)sub(repo.dir, "", path, fixed=TRUE),
  fig.height=4)
options(width=120)
if(FALSE){
  knitr::knit(paste0(post.id, ".Rmd"))
}
```

The goal of this blog post is to explain how to use
[nc](https://github.com/tdhock/nc) to parse log files, as we did in
[data.table-revdeps issue#7](
https://github.com/tdhock/data.table-revdeps/issues/7), to support our
NSF POSE funded project about expanding the open-source ecosystem
around R `data.table`.

## Example data to parse

```{r}

some.check.out <- "
* checking package dependencies ... ERROR
Package required but not available: 'Rcmdr'

Package suggested but not available for checking: 'tkrplot'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

* checking package dependencies ... ERROR
Packages required but not available:
  'adjclust', 'BiocGenerics', 'csaw', 'InteractionSet', 'limma',
  'SummarizedExperiment', 'HiCDOC'

* checking package dependencies ... NOTE
Package suggested but not available for checking: 'gWidgets2tcltk'
* checking if this is a source package ... OK

* checking package dependencies ... ERROR
Packages required but not available: 'maftools', 'NMF'

Packages suggested but not available for checking:
  'Biobase', 'Biostrings', 'BSgenome', 'BSgenome.Hsapiens.UCSC.hg19',
  'GenomicRanges', 'GenSA', 'IRanges'

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
* DONE
"

type.not.avail.pattern <- list(
  type='.*?',
  ' but not available')
nc::capture_all_str(some.check.out, type.not.avail.pattern)

up.to.colon.pattern <- list(
  type.not.avail.pattern,
  before.colon='.*?',
  ':')
nc::capture_all_str(some.check.out, up.to.colon.pattern)

one.or.more.line.non.greedy <- '(?:.*\n)+?'
up.to.deps.pattern <- list(
  up.to.colon.pattern,
  deps=one.or.more.line.non.greedy,
  "[*|\n]")
some.check.dt <- nc::capture_all_str(some.check.out, up.to.deps.pattern)
some.check.dt$deps
```

## Data files to parse

TODO download CSV and check not.avail column to download log files.

```{r}
local.dir <- "~/teaching/regex-tutorial/cran-check-logs"
dir.create(local.dir, showWarnings = FALSE)
```

TODO

```{r}
remote.url.prefix <- "https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-01-21/"
remote.csv <- paste0(remote.url.prefix, "full_list_of_jobs.csv")
jobs.dt <- data.table::fread(remote.csv)
not.avail.logs <- jobs.dt[not.avail>0]
for(pkg.i in 1:nrow(not.avail.logs)){
  pkg.row <- not.avail.logs[pkg.i]
  pkg.txt <- paste0(pkg.row$Package, ".txt")
  local.txt <- file.path(local.dir, pkg.txt)
  if(!file.exists(local.txt)){
    remote.txt <- paste0(remote.url.prefix, pkg.txt)
    download.file(remote.txt, local.txt)
  }
}
```

TODO

```{r}
log.txt.vec <- Sys.glob(file.path(local.dir, "*.txt"))
```

TODO

## Session info

```{r}
sessionInfo()
```
